[ci/fix] Explicitly uninstall Django before installing required version
In the "Install test dependencies" step,
the CI installs Django 4.2, which results in an
"ImportError: cannot import name 'DEFAULT_STORAGE_ALIAS' from 'django.conf'".
during the QA checks step.

To avoid this, we need to explicitly uninstall
Django before installing the required version.